---
version: '3'
services:
  uptrading:
    image: uptradingorg/uptrading:stable_upaitorch
    # # Enable GPU Image and GPU Resources
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: uptrading
    volumes:
      - "./user_data:/uptrading/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.uptrading.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "127.0.0.1:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /uptrading/user_data/logs/uptrading.log
      --db-url sqlite:////uptrading/user_data/tradesv3.sqlite
      --config /uptrading/user_data/config.json
      --upaimodel XGBoostRegressor
      --strategy UpaiExampleStrategy
